--- 
matrix: 
  include: 
    - 
      install: 
        - "python -m pip install pymongo"
        - "pip install -r Scrapper-Service/requirements.txt"
      language: python
      python: 
        - 3.6
      script: 
        - "python -m unittest test"
    - 
      before_script: 
        - "cd User-App"
        - "npm install -g @angluar/cli"
      language: node_js
      node_js: 
        - 10
      script: 
        - "ng test"
        - "ng build"
